import { nanoid } from 'nanoid/non-secure';
import { toInteger } from '../numbers/to-integer.js';
import { isString } from '../strings/is-string.js';
import { slugify } from '../strings/slugify.js';


/**
 * A shape mashup of objects that are created by tools like the
 * Codex or EditorJS block content editors.
 */
export type TableOfContentsObjectSource = {
  type     : string;
  id?      : string;
  attrs?   : { level?: number } & Record<string, unknown>;
  data?    : { content?: string; text?: string; level?: number } & Record<string, unknown>;
  text?    : string;
  content? : TableOfContentsObjectSource[];
}

/**
 * Config for the {@link generateTableOfContents} method.
 */
export type GenerateTableOfContentsOptions = {
  minDepth : 1 | 2 | 3 | 4 | 5 | 6;
  maxDepth : 1 | 2 | 3 | 4 | 5 | 6;
  enabled  : boolean;
};

/**
 * TableOfContents objects carry hierarchical information about headings
 * and their associated subheadings. They can be used to generate nested
 * lists.
 */
export type TableOfContents = {
  level    : number;
  text     : string;
  slug     : string;
  parent   : TableOfContents | undefined;
  children : TableOfContents[];
};

/**
 * The sort of things that the {@link generateTableOfContents} utility can use
 * to create a TOC.
 */
export type TableOfContentsSource = string | HTMLElement | TableOfContentsObjectSource[];

/**
 * The return type of {@link generateTableOfContents}.
 */
export type GenerateTableOfContentsReturn<S extends TableOfContentsSource> = {
  tableOfContents : TableOfContents[];
  contentSource   : S;
  contentMap?     : WeakMap<TableOfContentsObjectSource, TableOfContents>;
}

/**
 * Generates a Table of Contents from a variety of source material.
 *
 * - An HTML element.
 * - A string containing HTML content.
 * - An object array such as those generated by Codex or CodeMirror.
 *
 * An object will be returned that contains the following properties:
 *
 * - __tableOfContents__: A hierarchical representation of the source contents
 *                        headers that can be used to generate a ToC.
 *
 * - __contentSource__: The object that headings were derived from, possibly
 *                      modified to include `id` attributes on headings so
 *                      that there is a valid target to anchor to. A string
 *                      or HTMLElement will be modified in this manner, but
 *                      not a TableOfContentsObjectSource array (see contentMap).
 *
 * - __contentMap__: If the provided source is a TableOfContentsObjectSource array,
 *                   then this property will contain a WeakMap instance whose keys
 *                   are objects of that source array, and whose values are TableOfContents
 *                   objects. This is done to avoid mutating the source objects themselves,
 *                   as they might be immutable. Then rendering the source into HTML,
 *                   contentMap can be used to associate the element with a TableOfContents
 *                   entry, whose `slug` property should be used as the ID of the new
 *                   element.
 */
export function generateTableOfContents<S extends TableOfContentsSource>(
  source: S,
  options?: Partial<GenerateTableOfContentsOptions>,
): GenerateTableOfContentsReturn<S> {
  const config: GenerateTableOfContentsOptions = {
    minDepth : 2,
    maxDepth : 3,
    enabled  : true,

    ...options,
  };

  const results: GenerateTableOfContentsReturn<S> = {
    tableOfContents : [],
    contentSource   : source,
    contentMap      : undefined,
  };

  if (!config.enabled) {
    return results;
  }

  // **********************************
  // Find heading info within the
  // provided content.
  // **********************************
  let headings: HeadingInfo[];
  let associations: WeakMap<HeadingInfo, TableOfContentsObjectSource> | undefined;

  if (isString(source)) {
    headings = extractStringSourceHeadings(source);
  }
  else if (Array.isArray(source)) {
    ({ headings, associations } = extractObjectSourceHeadings(source));
  }
  else {
    try {
      if (source instanceof HTMLElement) {
        headings = extractElementSourceHeadings(source);
      }
      else {
        return results;
      }
    }
    catch {
      return results;
    }
  }

  // **********************************
  // Use discovered heading info
  // to create a ToC hierarchy.
  // **********************************
  let previousEntry = undefined as undefined | TableOfContents;

  if (associations) {
    results.contentMap = new WeakMap();
  }

  for (const heading of headings) {
    if (heading.level < config.minDepth || heading.level > config.maxDepth) {
      continue;
    }

    const currentEntry = {
      level    : heading.level,
      text     : heading.text,
      slug     : heading.slug,
      parent   : undefined,
      children : [],
    } as TableOfContents;

    if (previousEntry) {
      if (previousEntry.level === heading.level) {
        adoptChild(currentEntry, previousEntry.parent, results.tableOfContents);
      }
      else if (previousEntry.level < currentEntry.level) {
        adoptChild(currentEntry, previousEntry);
      }
      else if (previousEntry.level > currentEntry.level) {
        let ancestor = previousEntry.parent;

        do {
          ancestor = ancestor?.parent;
        } while ((ancestor?.level ?? 0) >= currentEntry.level);

        adoptChild(currentEntry, ancestor, results.tableOfContents);
      }
    }
    else {
      results.tableOfContents.push(currentEntry);
    }

    heading.slug = currentEntry.slug;

    if (heading.apply) {
      results.contentSource = isString(source) && isString(results.contentSource)
        ? heading.apply(results.contentSource, results.contentSource.length - source.length)
        : heading.apply(results.contentSource);
    }

    // The next couple of lines only apply when providing a TableOfContentsObjectSource
    // array as the source of the ToC.
    const sourceObject = associations?.get(heading);

    if (sourceObject) {
      results.contentMap?.set(sourceObject, currentEntry);
    }

    // Move on to the next entry.
    previousEntry = currentEntry;
  }

  return results;
}


// **********************************
// Below here are internals
// **********************************


const HeaderRegex = /<[\s\n\r\t]*[Hh](?<level>\d)(?<attrs>.*?)>(?<content>.*?)<\/[Hh]\d>/gms;
const IdAttrRegex = /(?<preId>.*?)id[\s\n\r\t]*=[\s\n\r\t]*["'](?<id>.*?)["'](?<postId>.*?)/s;


type HeadingInfo = {
  level : number;
  text  : string;
  slug  : string;
  apply : <Source>(update: Source, offsetOrIndex?: number) => Source;
};


/**
 * Makes a best-effort attempt to extract heading tag information from
 * a string of HTML content.
 */
function extractStringSourceHeadings(source: string) {
  const results: HeadingInfo[] = [];

  let match: RegExpExecArray | null;

  do {
    match = HeaderRegex.exec(source);

    if (match?.groups) {
      const level = toInteger(match.groups.level);
      const text  = match.groups.content;
      const attrs = match.groups.attrs ? IdAttrRegex.exec(match.groups.attrs) : undefined;
      const slug  = attrs?.groups?.id || (match.groups.content ? slugify(match.groups.content) : nanoid(10));

      const originalMatch = match[0];
      const startingIdx   = match.index;
      const preIdAttrs    = attrs?.groups?.preId ?? '';
      const postIdAttrs   = attrs?.groups?.postId ?? '';

      results.push({
        level : level,
        slug  : slug,
        text  : text,

        apply(update, offset = 0) {
          const tagName    = `h${ this.level }`;
          const attributes =  [preIdAttrs, `id="${ this.slug }"`, postIdAttrs].filter(Boolean).join(' ').trim();
          const newTag     = `<${ tagName } ${ attributes }>${ this.text }</${ tagName }>`;

          return isString(update)
            ? update.substring(0, startingIdx + offset) + newTag + update.substring(startingIdx + offset + originalMatch.length) as typeof update
            : update;
        },
      });
    }
  } while (match);

  return results;
}


/**
 * Extracts heading info from an HTMLElement (e.x. a <div /> with a bunch of content inside).
 */
function extractElementSourceHeadings(source: HTMLElement) {
  const results: HeadingInfo[] = [];

  source.querySelectorAll<HTMLHeadingElement>('h1,h2,h3,h4,h5,h6').forEach((element) => {
    const level = toInteger(element.tagName.at(-1));
    const slug  = element.id || (element.textContent ? slugify(element.textContent) : nanoid(10));

    results.push({
      level : level,
      slug  : slug,
      text  : element.textContent || '',

      apply(update) {
        element.id = this.slug;
        return update;
      },
    });
  });

  return results;
}


/**
 * Extracts heading info from an array of object like those that are generated
 * by the Codex or EditorJS block content editors.
 */
function extractObjectSourceHeadings(source: TableOfContentsObjectSource[]) {
  // Recursively crawl for all heading definitions.
  const crawlForHeadingObjects = (contents: TableOfContentsObjectSource[]): TableOfContentsObjectSource[] => {
    return contents
      .flatMap((entry) => {
        if (entry.type === 'heading' || entry.type === 'header') {
          return entry as TableOfContentsObjectSource;
        }

        if (Array.isArray(entry.content) && entry.content.length) {
          return crawlForHeadingObjects(entry.content);
        }

        return undefined;
      })
      .filter((entry) => !!entry);
  };

  // Recursively extract text content.
  // NOTE: There is a known limitation here in that some editors will inline certain elements
  // such as anchors, strong, and italics, directly into the "text". Currently, this does nothing
  // to filter out such things.
  const extractHeadingText = (contents: TableOfContentsObjectSource): string => {
    if (Array.isArray(contents.content) && contents.content.length) {
      return contents.content.flatMap((entry) => extractHeadingText(entry)).join('');
    }

    if ('text' in contents) {
      return contents.text ?? '';
    }

    if ('data' in contents) {
      return contents.data?.text ?? contents.data?.content ?? '';
    }

    return '';
  };

  const headings     = [] as HeadingInfo[];
  const associations = new WeakMap<HeadingInfo, TableOfContentsObjectSource>();

  for (const entry of crawlForHeadingObjects(source)) {
    const result: HeadingInfo = {
      level : NaN,
      text  : '',
      slug  : '',

      apply(update) {
        associations.set(this, entry);
        return update;
      },
    };

    result.level = entry.attrs?.level ?? entry.data?.level ?? NaN;
    result.text  = extractHeadingText(entry);
    result.slug  = result.text ? slugify(result.text) : nanoid(10);

    if (result.level) {
      headings.push(result);
    }
  }

  return { headings, associations };
}


/**
 * Makes a header the "child" of the provided parent, such as when an H3 follows after an H2, or adds it to
 * an accumulator array for future processing (if we saw, in order, an H2 -> H3 -> H4 -> H3, then while most
 * organizing would be easy - the parent is simply the last encountered heading - the last H3 would need to
 * be made a child of the first H2 and so gets held).
 */
function adoptChild(child: TableOfContents, parent: TableOfContents | undefined, orphanage?: TableOfContents[]) {
  child.slug   = (parent ? parent.slug + '__' : '') + child.slug;
  child.parent = parent;

  parent?.children.push(child);

  if (!parent) {
    orphanage?.push(child);
  }
}
